M48
; DRILL file {KiCad 7.0.6+dfsg-1} date qua 26 jul 2023 00:10:45
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-26T00:10:45-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
%
G90
G05
T1
X4.8796Y-2.874
T2
X3.3465Y-3.7008
X6.7717Y-2.9921
T0
M30
